version: pine-1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
install:
  - ps: |
      choco feature disable --name=showDownloadProgress
      choco install opencover.portable
      choco install codecov
build_script:
  - ps: |
      dotnet restore ./Stck.Tests/Stck.Tests.fsproj
      dotnet build ./Stck.Tests/Stck.Tests.fsproj
test_script:
  - ps: |
      cd ./Stck.Tests
      dotnet restore
      dotnet tool restore
      dotnet build
      dotnet minicover instrument --workdir ../ --assemblies Stck.Tests/bin/**/*.dll --sources Stck/**/*.fs
      dotnet minicover reset
      dotnet test --no-build
      dotnet minicover uninstrument --workdir ../
      dotnet minicover opencoverreport --workdir ../
      cd ..
after_test:
  - ps: codecov.exe -f "opencovercoverage.xml"
