version: ash-1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
install:
  - ps: |
      choco install opencover.portable --limit-output
      choco install codecov --limit-output
build_script:
  - ps: |
      dotnet restore ./Stck.Tests/Stck.Tests.fsproj
      dotnet build ./Stck.Tests/Stck.Tests.fsproj
test_script:
  - ps: |
      cd ./Stck.Tests
      dotnet restore
      dotnet tool restore
      dotnet build
      dotnet minicover instrument --workdir ../ --assemblies Stck.Tests/bin/**/*.dll --sources Stck/**/*.fs
      dotnet minicover reset
      dotnet test --no-build
      dotnet minicover uninstrument --workdir ../
      dotnet minicover opencoverreport --workdir ../
      cd ..
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "opencovercoverage.xml"
